# mysql db configs
# defaults
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: 'quagmire1'
  host: localhost
  port: 3306

# development/test db
development:
  database: crossover_dev
  <<: *defaults

test:
  database: crossover_tst
  <<: *defaults

# production db
# production:
  # database: crossover_prd
  # <<: *defaults